# Inspect Summary Database
View raw transcripts and AI-generated summaries stored in `data/transcripts.db`.

In [1]:
import os
import sys
from pathlib import Path

# Ensure working directory is the project root, not notebooks/
if Path.cwd().name == "notebooks":
    os.chdir("..")
sys.path.insert(0, ".")

from src.database.transcript_db import TranscriptDatabase
import pandas as pd

pd.set_option("display.max_colwidth", 300)
pd.set_option("display.max_columns", None)

db = TranscriptDatabase()

09:36:26 - INFO - Logger initialized. Log file: logs/transcript_db_20260304.log
09:36:26 - INFO - TranscriptDatabase ready — data/transcripts.db

## Transcripts

In [2]:
transcripts = db.load()
print(f"{len(transcripts)} transcript(s) in database")
transcripts[["video_id", "channel", "title", "published_at", "transcript_available"]]

09:36:26 - INFO - load() — returned 4 row(s).

4 transcript(s) in database

,video_id,channel,title,published_at,transcript_available
0,p6aTUw6Cku8,TwicebakedJake,What's Hot & What's Not in an Explosive Pokemon Market,2026-03-03T21:00:52Z,True
1,p2Tigg4zyGs,TwicebakedJake,THE XY PREMIUM TRAINER'S COLLECTION!,2026-02-27T17:01:31Z,True
2,nP-1vDE-gWU,okJLUV,These Should Be Pokemon Cards (Trust Me),2026-02-27T12:57:13Z,True
3,u8CqdgoKBus,okJLUV,Card Artist Spotlight: Megumi Mizutani (Where Did They Go?),2026-02-21T11:34:16Z,True

## Summaries

In [3]:
summaries = db.load_summaries()
print(f"{len(summaries)} summary/summaries in database")
summaries[["video_id", "model_used", "created_at"]]

09:36:26 - INFO - load_summaries() — returned 4 row(s).

4 summary/summaries in database

      video_id                 model_used                        created_at
0  p6aTUw6Cku8  claude-haiku-4-5-20251001  2026-03-04T01:35:07.261966+00:00
1  p2Tigg4zyGs  claude-haiku-4-5-20251001  2026-03-04T01:35:17.479373+00:00
2  nP-1vDE-gWU  claude-haiku-4-5-20251001  2026-03-04T01:35:20.757046+00:00
3  u8CqdgoKBus  claude-haiku-4-5-20251001  2026-03-04T01:35:27.550033+00:00

## Summaries joined with Transcript metadata

In [4]:
merged = summaries.merge(
    transcripts[["video_id", "channel", "title", "url"]], on="video_id"
)
merged[["channel", "title", "model_used", "created_at", "url"]]

,channel,title,model_used,created_at,url
0,TwicebakedJake,What's Hot & What's Not in an Explosive Pokemon Market,claude-haiku-4-5-20251001,2026-03-04T01:35:07.261966+00:00,https://www.youtube.com/watch?v=p6aTUw6Cku8
1,TwicebakedJake,THE XY PREMIUM TRAINER'S COLLECTION!,claude-haiku-4-5-20251001,2026-03-04T01:35:17.479373+00:00,https://www.youtube.com/watch?v=p2Tigg4zyGs
2,okJLUV,These Should Be Pokemon Cards (Trust Me),claude-haiku-4-5-20251001,2026-03-04T01:35:20.757046+00:00,https://www.youtube.com/watch?v=nP-1vDE-gWU
3,okJLUV,Card Artist Spotlight: Megumi Mizutani (Where Did They Go?),claude-haiku-4-5-20251001,2026-03-04T01:35:27.550033+00:00,https://www.youtube.com/watch?v=u8CqdgoKBus

## Read a Summary

In [5]:
from IPython.display import Markdown

for _, row in merged.iterrows():
    display(Markdown(f"### [{row['title']}]({row['url']})"))
    display(
        Markdown(
            f"*Channel: {row['channel']} | Model: {row['model_used']} | {row['created_at']}*"
        )
    )
    display(Markdown(row["summary"]))
    display(Markdown("---"))

### [What's Hot & What's Not in an Explosive Pokemon Market](https://www.youtube.com/watch?v=p6aTUw6Cku8)

*Channel: TwicebakedJake | Model: claude-haiku-4-5-20251001 | 2026-03-04T01:35:07.261966+00:00*

# What's Hot & What's Not in an Explosive Pokemon Market — March 2026
**Channel:** TwicebakedJake

---

## WHAT'S HOT

### Sealed Products
- **151 UPC**: All-time high of ~$700 (criticized as overvalued; climbing too quickly despite availability)
- **Charizard UPC**: ~$480 (contains 3 Charizard promos + Evolving Skies packs at $40+)
- **Paldean Fates ETB**: $300 (was $50 at Costco 1.5 years ago; year-over-year climb from $200 to $500)

### Modern Singles
- **Charizard EX (151)**: $360, up from $260 (1-2 months prior); rapid spike
- **Charmander Illustration Rare (151)**: Spiking as set reaches perceived end-of-life
- **Mega Gengar EX (Ascended Heroes)**: Only climbing card in set; shifted from decline to retrace. Raw copy: $500+ (up from <$100 one year prior)
- **Greninja ex (Shrouded Fable promo)**: Climbing due to single wave release, never restocked; limited supply
- **Special Delivery Charizard**: Finally climbing after slow steady buyout; took 5-6 years from initial $100 release to gain traction

### Vintage
- **Sabrina's Gengar & Vintage Gengar cards**: Hottest Pokemon in vintage market by far; very low PSA 10 pop counts; cards "skyrocketing"
- Note: Umbreon, Charizard, and Pikachu historically popular but Gengar now dominates

---

## WHAT'S NOT HOT

### Sealed Products
- **Prismatic Evolution Surprise Box**: Restocked repeatedly; prices dipped; promo cards undervalued
- **Surging Sparks Booster Box**: $250 (was $260 in March 2025); speculated as S-tier but became "old news"; restocked multiple times
- **Pokémon Center Promo Boxes (Tohoku, etc.)**: $160 (down from $200-300+ summer/fall 2025); restocked, difficult to move at vendor shows

### Modern Singles
- **Charizard V Secret Rare (Champions Path)**: Flatline price; overshadowed by superior Charizard printings; generates no collector excitement
- **Suicune V (Crown Zenith)**: Cool artwork but not climbing despite sealed pack increases
- **Mega Ultra Rare Cards**: Not climbing; collector preference shifted to Special Illustration Rares (SIRs), which command higher prices than Mega Ultra Rares
  - Mega Charizard SIR outpaces Mega Ultra Rare counterpart
  - Mega Garchomp EX & Mega Lucario EX: consistently dropping
- **Paradox Pokémon & Iron Crown EX (Ancient Roar/Future Flash)**: New-gen designs underperforming; nostalgia Pokemon (Mewtwo, Charizard, Gengar, Pikachu) consistently outperform

### Vintage Singles
- **Reshiram (Radiant Collection)**: Flatlined around $100 after mid-2025 spike; appears to be price ceiling for many cards

---

## KEY MARKET INSIGHTS

- **Recency Bias**: Speculative market heavily favors products from last 2-3 years; 151 and Paldean Fates overheated
- **Restocks Kill Value**: Repeated retailer restocking (Surging Sparks, Prismatic Evolution, Pokémon Center boxes) depresses prices despite quality sets
- **Supply vs. Demand**: Cards require both popularity AND limited supply to climb (e.g., Greninja ex's single wave release; vintage Gengar low PSA 10 pop counts)
- **Set Lifecycle**: "Best set of yesterday might be worst set of today" — newer sets (Mewtwo's Mega Evolution, Charizard ex Blooming Flames, Ascended Heroes) outpace older competitors
- **Sealed > Singles Paradox**: Sealed products climb as supply decreases, but individual chase singles sometimes plateau or decline despite sealed growth
-

---

### [THE XY PREMIUM TRAINER'S COLLECTION!](https://www.youtube.com/watch?v=p2Tigg4zyGs)

*Channel: TwicebakedJake | Model: claude-haiku-4-5-20251001 | 2026-03-04T01:35:17.479373+00:00*

# Summary: The XY Premium Trainer's Collection

## Product Overview
- **Product**: XY Premium Trainer's Collection box
- **Release Date**: November 17, 2017
- **Original MSRP**: $99.99
- **Current Market Price**: ~$1,850
- **Contents**: 2 booster packs + 14 promo cards

## Market History & Sentiment
- Poorly received at launch due to perceived poor value proposition (only 2 packs + 14 promos for $100)
- Secondary market price dropped below retail ($80) during 2018-2020
- Promo cards were inexpensive at release ($2-3 each for common promos)
- Has since become one of the most desirable XY-era products, with significant appreciation over 8 years

## Notable Cards & Valuations
**Most Valuable Promo Cards:**
- Shaman EX (Gold Secret Rare): ~$4,000 (PSA 10)
- Yatel/Yveltal (Gold Secret Rare): similarly priced
- Complete PSA 10 graded collection: $24,000-$25,000
- Combined ungraded value of all 14 promos: ~$1,400
- Cheaper PSA 10 examples (Mega Sharpedo, Mega Aegislash): $400-500 minimum

**Other notable cards**: Delinquent, Blacksmith, Team Rocket's Grunt, Shauna, N

## Grading Commentary
- **Critical Issue**: Cards commonly arrive with manufacturing defects (corner chipping, bent corners, edge wear)
- Plastic holder compression caused significant damage over time
- Realistic grading expectations: 80% will grade PSA 8-9; 15-20% potentially PSA 10; 0% black label possible
- Population reports extremely low (most cards under 100 copies graded)
- Minimal whitening observed; primary damage from corner/edge wear

## Booster Pack Contents & Pricing
- **XY Roaring Skies**: Current pack price ~$60; best hit is Rayquaza
- **XY Primal Clash**: Current pack price ~$50; best hits are Groudon/Kyogre (yellow border holos)

## Competitive/Market Takeaway
- Product was rejected due to poor pack-to-promo ratio; Pokemon Company never replicated this product structure
- Now considered "cream of the crop" for XY-era collectibles despite initial poor reception
- Strong investment appreciation over 8 years, though grading quality issues limit PSA 10 potential

---

### [These Should Be Pokemon Cards (Trust Me)](https://www.youtube.com/watch?v=nP-1vDE-gWU)

*Channel: okJLUV | Model: claude-haiku-4-5-20251001 | 2026-03-04T01:35:20.757046+00:00*

# Summary: "These Should Be Pokemon Cards (Trust Me)"

**Channel:** okJLUV

**Content Type:** Illustrator/Artist Spotlight

**Key Focus:**
- Showcases 30th Anniversary Pokémon artwork created by professional illustrators known for designing popular Pokémon TCG cards
- Highlights fan-favorite card artists and their original artwork
- Emphasizes aesthetic quality and design merit of the pieces shown

**Notable Elements:**
- "Heat" (repeated) — apparent commentary on the quality of artwork being featured
- Promotional call-to-action encouraging viewers to follow the featured illustrators on social media

**Investment/Market Relevance:** None identified

**Cards/Sets Discussed:** None specifically named

**Notable Pulls/Openings:** None

**Price Data:** None

**Note:** This video appears to be primarily an art appreciation/illustrator highlight content rather than TCG investment, market analysis, or pack opening content. No specific card valuations, market movements, or investment signals are present in the transcript.

---

### [Card Artist Spotlight: Megumi Mizutani (Where Did They Go?)](https://www.youtube.com/watch?v=u8CqdgoKBus)

*Channel: okJLUV | Model: claude-haiku-4-5-20251001 | 2026-03-04T01:35:27.550033+00:00*

# Card Artist Spotlight: Megumi Mizutani — Summary

## Artist Overview
The video profiles **Megumi Mizutani**, a prominent Pokémon TCG illustrator from the Black & White era onward who has been notably absent from the game since 2025.

## Notable Cards Illustrated

**Trainer Cards (Full Art):**
- Shauntal (Freezebolt)
- Professor Sycamore (2014 Japan Gym promo pack)
- Jesse and James (full art version, Sun & Moon era)
- Valerie (V-Max Climax, with Sylveon)
- N with Zoroark EX (Battle Partners)

**Pokémon Cards:**
- Pansage (Hail Blizzard — her first card)
- Typhlosion (Blue Shock)
- Mega Gardevoir EX (Pokémon XY)
- Wobbuffet (Super Burst Impact)
- Dragonite (Tag Bolt)
- Sylveon GX (Dreamly — Special Art, helped reintroduce Partner Pokémon mechanic)
- Sylveon V-Max Climax (described as "arguably the best depiction")
- **Pikachu with Jolteon and Electabuzz** — described as "extremely rare" and "highly coveted," with a fierce, game-inspired depiction unlike any card since

**Recent Work:**
- Team Rocket's Meowth (Destiny set) — one of only three cards illustrated by Mizutani in 2025

## Artistic Style Evolution
- Early work: Thin line work, soft white glow, 2000's manga influence
- Sun & Moon era: Shift to lively backgrounds, anime vibe
- Recurring traits: Thick black outlines, two-tone coloring, dynamic character poses, blurred background elements

## Market/Collectibility Notes
- The Pikachu card is noted as exceptionally rare and highly sought after
- Mizutani's full art trainers are described as iconic and foundational to the full art trainer category as it exists today
- Notable absence from releases despite her historical significance

---

## Pending (unsummarized transcripts)

In [6]:
pending = db.get_unsummarized_transcripts()
print(f"{len(pending)} transcript(s) not yet summarized")
if not pending.empty:
    display(pending[["video_id", "channel", "title"]])

09:36:26 - INFO - get_unsummarized_transcripts() — 0 transcript(s) pending summarization.

0 transcript(s) not yet summarized