# Inspect Verification Database
View verification reports, sources, price data, and buy recommendations stored in `data/transcripts.db`.

In [1]:
import json
import os
import sqlite3
import sys
from pathlib import Path

# Ensure working directory is the project root, not notebooks/
if Path.cwd().name == "notebooks":
    os.chdir("..")
sys.path.insert(0, ".")

from src.database.transcript_db import TranscriptDatabase
import pandas as pd

pd.set_option("display.max_colwidth", 300)
pd.set_option("display.max_columns", None)

db = TranscriptDatabase()

16:45:18 - INFO - Logger initialized. Log file: logs/transcript_db_20260408.log
16:45:18 - INFO - TranscriptDatabase ready — data/transcripts.db

## Verifications

In [2]:
with sqlite3.connect(db.db_path) as conn:
    verifications = pd.read_sql_query("SELECT * FROM verifications", conn)

print(f"{len(verifications)} verification(s) in database")
verifications[["video_id", "model_used", "verified_at"]]

5 verification(s) in database

      video_id                 model_used                       verified_at
0  p6aTUw6Cku8  claude-haiku-4-5-20251001  2026-03-05T03:06:46.223367+00:00
1  1KijlyGIm0g  claude-haiku-4-5-20251001  2026-03-05T03:07:08.953466+00:00
2  3lj68hbPojQ  claude-haiku-4-5-20251001  2026-04-07T04:53:08.702900+00:00
3  awdv1xidtGw  claude-haiku-4-5-20251001  2026-04-07T04:53:19.340993+00:00
4  2u9GyPkR3y8  claude-haiku-4-5-20251001  2026-04-08T08:45:03.801093+00:00

## Verifications joined with Transcript metadata

In [3]:
transcripts = db.load()
merged = verifications.merge(
    transcripts[["video_id", "channel", "title", "url"]], on="video_id"
)
merged[["channel", "title", "model_used", "verified_at", "url"]]

16:45:18 - INFO - load() — returned 5 row(s).

,channel,title,model_used,verified_at,url
0,TwicebakedJake,What's Hot & What's Not in an Explosive Pokemon Market,claude-haiku-4-5-20251001,2026-03-05T03:06:46.223367+00:00,https://www.youtube.com/watch?v=p6aTUw6Cku8
1,Danny Phantump,Day 208 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemoncards #pokemontcg,claude-haiku-4-5-20251001,2026-03-05T03:07:08.953466+00:00,https://www.youtube.com/watch?v=1KijlyGIm0g
2,TwicebakedJake,How Buying Cards in 2026 Feels Like,claude-haiku-4-5-20251001,2026-04-07T04:53:08.702900+00:00,https://www.youtube.com/watch?v=3lj68hbPojQ
3,Danny Phantump,Day 241 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemontcg #pokemoncards,claude-haiku-4-5-20251001,2026-04-07T04:53:19.340993+00:00,https://www.youtube.com/watch?v=awdv1xidtGw
4,Danny Phantump,Day 242 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemontcg #pokemoncards,claude-haiku-4-5-20251001,2026-04-08T08:45:03.801093+00:00,https://www.youtube.com/watch?v=2u9GyPkR3y8

## Verification Reports

In [4]:
from IPython.display import Markdown

for _, row in merged.iterrows():
    display(Markdown(f"### [{row['title']}]({row['url']})"))
    display(
        Markdown(
            f"*Channel: {row['channel']} | Model: {row['model_used']} | {row['verified_at']}*"
        )
    )
    display(Markdown(row["verification_report"]))
    display(Markdown("---"))

### [What's Hot & What's Not in an Explosive Pokemon Market](https://www.youtube.com/watch?v=p6aTUw6Cku8)

*Channel: TwicebakedJake | Model: claude-haiku-4-5-20251001 | 2026-03-05T03:06:46.223367+00:00*

## Price Verification

### Charizard UPC
Seem the Pokémon TCG Mega Charizard X ex UPC are not Selling at GameStop due to the Price tag being $199.99 ($119.99 MSRP) It even available on | OK | Pokemon Mega Charizard X ex 023 Black Star Promo UPC English CGC 10 Graded #023 [eBay] | $99.95 |  | Report It |. OK | Pokemon Mega Charizard X ex 023 Black Star Promo UPC English CGC 10 Graded #023 [eBay] | $120.00   $168.00 | $168.00 | Report It |. OK | Pokemon Mega Charizard X ex 023 Black S

### Charizard EX (151 set)
But copies of Charizard ex were fetching prices of $300 by the end of February, and the card has since lost about $70 in value, with near mint | Charizard EX Holo Rare Pokémon TCG Card 183/165 Scarlet & Violet 151 PSA 8 183/165 [eBay], $30.00, Report It. See an incorrect/misclassified sale? Please click

### Charmander Illustration Rare (151)
Charmander 168/165 Pokemon Sv: Scarlet & Violet 151 Holo Full Art Illustration. Charmander 168/165 Sv: Scarlet & Violet 151 Holo PSA certified Miscut Very Rare. LP Raw: Charmander 168/165 Sv: Scarlet & Violet 151 Holo. Charmander 168/165 Sv: Scarlet & Violet 151 Holo. Charmander 168/165 Sv: Scarlet  | Image 7: Go to: Content TCGplayer Gift Cards product listings. Image 8: Go to: Content TCGplayer Gift Cards product listings. Image 27: Venusaur #### SV: Scarlet & Violet 151 Illustration Rare, #169/165 Charmeleon - 169/165 47 listings from $43.63 Market Price:$69.47. Image 28: Venusaur #### SV: Sca

### Mega Gengar EX (Ascended Heroes)
Ascended Heroes. Card No. #125. Rarity. Double Rare Holo. All Time High. $0.00. All Time Low. $0.00. Mega Gengar ex's Price History. 1 Month 6 Months 1 Year. | Holofoil: $950.42 ; Market Price, $950.42 ; Most Recent Sale, $1,074.97 ; Listed Median: - ; Current Quantity: 14, Current Sellers: 12

### Greninja ex (Shrouded Fables promo)
Pokémon TCG Greninja EX SVP132 Shrouded Fable Black Star Promo Card #132 [eBay], $51.23, Report It. 2026-02-27. Time Warp shows photos of completed sales | The Pokémon TCG card Greninja Ex 132 is soaring in value, now worth about $60 when last summer its boxed product sold for half that.

---

### [Day 208 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemoncards #pokemontcg](https://www.youtube.com/watch?v=1KijlyGIm0g)

*Channel: Danny Phantump | Model: claude-haiku-4-5-20251001 | 2026-03-05T03:07:08.953466+00:00*

## Price Verification

### Drizzile Baby Shiny
Drizzile 225/190 S Shiny Star V Pokemon Card Japanese NM-Mint TCG Baby Shiny S4aGBP 3.04Free Shipping. | Holofoil: $3.40 ; Market Price, $3.33 ; Most Recent Sale, $2.75 ; Listed Median: - ; Current Quantity: 158, Current Sellers: 109

### Corviknight Baby Shiny
The Shiny Corviknight Graded Card has a current estimated value of $23 USD, which has changed by -23 percent this month. Monthly USD Price Over Time. | At the current market price of $1.16, Corviknight is an accessible entry point for collectors. The current price makes it suitable for beginners or those

### Charizard V-Max
Pokemon. Find something awesome ; Holofoil: $178.44 ; Market Price, $143.89 ; Most Recent Sale, $160.00 ; Listed Median: -. | Market Price, $134.04 ; Most Recent Sale, $118.00 ; Listed Median: - ; Current Quantity: 91, Current Sellers: 75 ; Total Sold: 154, Avg. Daily Sold: 2

### Crobat Baby Shiny
Market Price, $73.22 ; Most Recent Sale, $87.99 ; Listed Median: $93.99 ; Current Quantity: 17, Current Sellers: 8 ; Total Sold: 13, Avg. Daily Sold: - | Includes seven Shining Fates booster packs; one foil promo card featuring either Shiny Crobat ... Regular price $6.00 CAD Sale price $5.22 CAD. Unit price

---

### [How Buying Cards in 2026 Feels Like](https://www.youtube.com/watch?v=3lj68hbPojQ)

*Channel: TwicebakedJake | Model: claude-haiku-4-5-20251001 | 2026-04-07T04:53:08.702900+00:00*

No cards identified for verification.

---

### [Day 241 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemontcg #pokemoncards](https://www.youtube.com/watch?v=awdv1xidtGw)

*Channel: Danny Phantump | Model: claude-haiku-4-5-20251001 | 2026-04-07T04:53:19.340993+00:00*

## Price Verification

### Rocket's Moltres EX
Team Rocket's Moltres ex. Open in TCGplayer. $0.89. Holofoil. Buy Now. Add to ... Discover authentic Japanese Pokémon cards. Browse, track prices, and add | Team Rocket's Moltres Ex Pokémon TCG Cards ; Destined Rivals Stamped Team Rocket Moltres EX Special Illustration Rare 229/182 · $74.99. Free shipping. Only 1 left

---

### [Day 242 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemontcg #pokemoncards](https://www.youtube.com/watch?v=2u9GyPkR3y8)

*Channel: Danny Phantump | Model: claude-haiku-4-5-20251001 | 2026-04-08T08:45:03.801093+00:00*

No cards identified for verification.

---

## Sources

In [5]:
for _, row in merged.iterrows():
    sources = json.loads(row["sources"])
    display(Markdown(f"### [{row['title']}]({row['url']})"))
    if sources:
        display(Markdown("\n".join(f"- {s}" for s in sources)))
    else:
        display(Markdown("*No sources found.*"))
    display(Markdown("---"))

### [What's Hot & What's Not in an Explosive Pokemon Market](https://www.youtube.com/watch?v=p6aTUw6Cku8)

- https://www.facebook.com/PokemonGlobalNews/posts/seem-the-pok%C3%A9mon-tcg-mega-charizard-x-ex-upc-are-not-selling-at-gamestop-due-to-/854332903911854/
- https://www.pricecharting.com/game/pokemon-promo/mega-charizard-x-ex-23
- https://www.reddit.com/r/PokeInvesting/comments/1pq6f0o/mega_charizard_upc_its_promo_cards/
- https://www.ebay.com/itm/406606151780
- https://www.ebay.com/itm/227042740974
- https://www.ebay.com/itm/157407853990
- https://www.wargamer.com/pokemon-trading-card-game/charizard-ex-151-falling-value
- https://www.pricecharting.com/game/pokemon-scarlet-&-violet-151/charizard-ex-183
- https://www.psacard.com/en-CA/auctionprices/tcg-cards/2023-pokemon-mew-en-151/charizard-ex/9603030
- https://www.ebay.com/shop/charizard-151-set?_nkw=charizard+151+set
- https://www.ebay.com/itm/315615522163
- https://www.ebay.com/itm/358061651563
- https://www.tcgplayer.com/product/502556/pokemon-sv-scarlet-and-violet-151-charmander-168-165?srsltid=AfmBOoqTMCEa9Yn7z2qvItqKjryJRT3VmU5HmSaR3Eo6QrsK9M-X1KPJ
- https://www.boisecardshop.com/product-page/charmander-illustration-rare-scarlet-violet-151
- https://www.ebay.com/shop/charmander-151-english?_nkw=charmander+151+english
- https://www.ebay.com/itm/405661715007
- https://www.digitaltq.com/pokemon-tcg/ascended-heroes/mega-gengar-ex-125
- https://www.tcgplayer.com/product/676096/pokemon-me-ascended-heroes-mega-gengar-ex-284-217?srsltid=AfmBOoqELbL858ZpGH_AeuIzrD3EvlCCvfmLQrRCIDH2QWxCNGPxoKx2
- https://www.pokedata.io/card/Ascended+Heroes/Mega+Gengar+284
- https://www.ebay.com/itm/366181848721
- https://www.ebay.com/itm/397552999751
- https://www.ebay.com/itm/406715372423
- https://www.pricecharting.com/game/pokemon-promo/greninja-ex-132
- https://www.wargamer.com/pokemon-trading-card-game/greninja-ex-price-spike
- https://www.psacard.com/auctionprices/tcg-cards/2024-pokemon-svp-en-sv-black-star-promo/greninja-ex/11562019
- https://www.ebay.com/itm/365044950593
- https://www.ebay.com/itm/117052825183?epid=3071602373&itmmeta=01KJ6V3Q552Y6J28B3W8WGG5VM&hash=item1b40e45e5f:g:u3oAAeSwWpdpm~bQ&itmprp=enc%3AAQALAAAA4DKQclQvzFwZQpmMrsO4Lup8TfyvMH9vgdP6ryXSlHPMFpWiOM4o94gYvzXkLgHOqbg3JbfJlGDa7OzO300Le7cO73JdOy%2FPCyY4TRSo7FJIjPcZBvHTLl%2F%2BO6aF7ZeNtTr7xpZefga%2BXOG9C%2Bkwv3mJVGrn3wHXt8wxxbDsSI1O1nRxDEgJeh9YCIzfEwqfBNwM1CmxuLRPSZqCK1Ms762%2F%2B2xHxuUf78ZGgSq%2B%2BCPt2pvHdzg6bYVhPHh4S7eCyPszexzHvT%2BegaQII%2F1eHniLe%2BYoLLJ7pj%2Fpp%2Bw2sbt7%7Ctkp%3ABk9SR4LzjtuRZw
- https://www.ebay.com/itm/177571189650

---

### [Day 208 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemoncards #pokemontcg](https://www.youtube.com/watch?v=1KijlyGIm0g)

- https://www.pricecharting.com/game/pokemon-japanese-shiny-star-v/drizzile-225
- https://www.tcgplayer.com/product/232377/pokemon-shining-fates-shiny-vault-drizzile?srsltid=AfmBOopaPckPepPcUtWiTg4jAcVz8nTAHLTlUyDhkPxeuybpAih89kWP
- https://www.pricecharting.com/game/pokemon-shining-fates/drizzile-sv026
- https://www.ebay.com/itm/226767160406
- https://www.ebay.com/itm/205470719754
- https://tcgprice.guide/collectible/shiny-corviknight-trading-card-graded/
- https://pokescope.app/card/swsh45sv-SV089/
- https://www.pricecharting.com/game/pokemon-shining-fates/corviknight-sv089
- https://www.ebay.com/itm/126865193741
- https://www.ebay.com/itm/155915663115
- https://www.ebay.com/itm/227157271041
- https://www.tcgplayer.com/product/223073/pokemon-champions-path-charizard-vmax-secret?srsltid=AfmBOorp4CIsWCW8E7q-NKgUxROM8nLpjSu7zygcswvPrIBXKnaLgK63
- https://www.tcgplayer.com/product/232496/pokemon-shining-fates-shiny-vault-charizard-vmax?srsltid=AfmBOor_Gu0h9SK9rj3YCG4fkbOHmjos974aJ67_aD3oIMJ4YjljX3Ar
- https://il.ebay.com/b/Charizard-VMAX-Pokemon-TCG-Cards/2536/bn_7124861080
- https://www.ebay.com/itm/316370997918
- https://www.ebay.com/itm/225551311626
- https://www.ebay.com/itm/406182725033
- https://www.tcgplayer.com/product/230391/pokemon-shining-fates-shining-fates-premium-collection-shiny-crobat?srsltid=AfmBOorIrJfDIHxO6uddlXE7GAOsjVJZp5HGMfAAGPQ4qIdBPbr9DCRX
- https://sportslatornade.com/products/pokemon-tcg-shining-fates-premium-collection-shiny-crobat-shining-fates?srsltid=AfmBOopuuCJLVAZevQ99gCFyjyN1Gqs2AjCANdQEHN5lLMdce5KZNzn2
- https://store.401games.ca/products/pokemon-shining-fates-premium-collection-crobat-v?srsltid=AfmBOooV77rl2WcFrCD9IxlXNHI92hEtHl7xU9jJkTFjUYGc5UhqNWvr
- https://www.ebay.com/itm/403914564317
- https://www.ebay.com/itm/265304976115
- https://www.ebay.com/itm/388462829741

---

### [How Buying Cards in 2026 Feels Like](https://www.youtube.com/watch?v=3lj68hbPojQ)

*No sources found.*

---

### [Day 241 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemontcg #pokemoncards](https://www.youtube.com/watch?v=awdv1xidtGw)

- https://pokescreener.com/set/sv10/card/31
- https://www.ebay.com/b/Team-Rockets-Moltres-Ex-Pokemon-TCG-Cards/2536/bn_7124870691
- https://www.pricecharting.com/game/pokemon-destined-rivals/team-rocket%27s-moltres-ex-229
- https://www.ebay.com/itm/318053227174
- https://www.ebay.com/itm/388914584793

---

### [Day 242 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemontcg #pokemoncards](https://www.youtube.com/watch?v=2u9GyPkR3y8)

*No sources found.*

---

## Price Data

In [6]:
for _, row in merged.iterrows():
    price_data = json.loads(row["price_data"])
    display(Markdown(f"### [{row['title']}]({row['url']})"))
    if price_data:
        price_df = pd.DataFrame(
            [{"card": card, "data": info} for card, info in price_data.items()]
        )
        display(price_df)
    else:
        display(Markdown("*No price data found.*"))
    display(Markdown("---"))

### [What's Hot & What's Not in an Explosive Pokemon Market](https://www.youtube.com/watch?v=p6aTUw6Cku8)

,card,data
0,Charizard UPC,Seem the Pokémon TCG Mega Charizard X ex UPC are not Selling at GameStop due to the Price tag being $199.99 ($119.99 MSRP) It even available on | OK | Pokemon Mega Charizard X ex 023 Black Star Promo UPC English CGC 10 Graded #023 [eBay] | $99.95 | | Report It |. OK | Pokemon Mega Charizard X e...
1,Charizard EX (151 set),"But copies of Charizard ex were fetching prices of $300 by the end of February, and the card has since lost about $70 in value, with near mint | Charizard EX Holo Rare Pokémon TCG Card 183/165 Scarlet & Violet 151 PSA 8 183/165 [eBay], $30.00, Report It. See an incorrect/misclassified sale? Plea..."
2,Charmander Illustration Rare (151),Charmander 168/165 Pokemon Sv: Scarlet & Violet 151 Holo Full Art Illustration. Charmander 168/165 Sv: Scarlet & Violet 151 Holo PSA certified Miscut Very Rare. LP Raw: Charmander 168/165 Sv: Scarlet & Violet 151 Holo. Charmander 168/165 Sv: Scarlet & Violet 151 Holo. Charmander 168/165 Sv: Scar...
3,Mega Gengar EX (Ascended Heroes),"Ascended Heroes. Card No. #125. Rarity. Double Rare Holo. All Time High. $0.00. All Time Low. $0.00. Mega Gengar ex's Price History. 1 Month 6 Months 1 Year. | Holofoil: $950.42 ; Market Price, $950.42 ; Most Recent Sale, $1,074.97 ; Listed Median: - ; Current Quantity: 14, Current Sellers: 12"
4,Greninja ex (Shrouded Fables promo),"Pokémon TCG Greninja EX SVP132 Shrouded Fable Black Star Promo Card #132 [eBay], $51.23, Report It. 2026-02-27. Time Warp shows photos of completed sales | The Pokémon TCG card Greninja Ex 132 is soaring in value, now worth about $60 when last summer its boxed product sold for half that."

---

### [Day 208 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemoncards #pokemontcg](https://www.youtube.com/watch?v=1KijlyGIm0g)

,card,data
0,Drizzile Baby Shiny,"Drizzile 225/190 S Shiny Star V Pokemon Card Japanese NM-Mint TCG Baby Shiny S4aGBP 3.04Free Shipping. | Holofoil: $3.40 ; Market Price, $3.33 ; Most Recent Sale, $2.75 ; Listed Median: - ; Current Quantity: 158, Current Sellers: 109"
1,Corviknight Baby Shiny,"The Shiny Corviknight Graded Card has a current estimated value of $23 USD, which has changed by -23 percent this month. Monthly USD Price Over Time. | At the current market price of $1.16, Corviknight is an accessible entry point for collectors. The current price makes it suitable for beginners..."
2,Charizard V-Max,"Pokemon. Find something awesome ; Holofoil: $178.44 ; Market Price, $143.89 ; Most Recent Sale, $160.00 ; Listed Median: -. | Market Price, $134.04 ; Most Recent Sale, $118.00 ; Listed Median: - ; Current Quantity: 91, Current Sellers: 75 ; Total Sold: 154, Avg. Daily Sold: 2"
3,Crobat Baby Shiny,"Market Price, $73.22 ; Most Recent Sale, $87.99 ; Listed Median: $93.99 ; Current Quantity: 17, Current Sellers: 8 ; Total Sold: 13, Avg. Daily Sold: - | Includes seven Shining Fates booster packs; one foil promo card featuring either Shiny Crobat ... Regular price $6.00 CAD Sale price $5.22 CAD..."

---

### [How Buying Cards in 2026 Feels Like](https://www.youtube.com/watch?v=3lj68hbPojQ)

*No price data found.*

---

### [Day 241 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemontcg #pokemoncards](https://www.youtube.com/watch?v=awdv1xidtGw)

,card,data
0,Rocket's Moltres EX,"Team Rocket's Moltres ex. Open in TCGplayer. $0.89. Holofoil. Buy Now. Add to ... Discover authentic Japanese Pokémon cards. Browse, track prices, and add | Team Rocket's Moltres Ex Pokémon TCG Cards ; Destined Rivals Stamped Team Rocket Moltres EX Special Illustration Rare 229/182 · $74.99. Fre..."

---

### [Day 242 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemontcg #pokemoncards](https://www.youtube.com/watch?v=2u9GyPkR3y8)

*No price data found.*

---

## Buy Recommendations

In [7]:
summaries = db.load_summaries()
refined = summaries[summaries["buy_recommendations"].notna()].merge(
    transcripts[["video_id", "channel", "title", "url"]], on="video_id"
)

print(f"{len(refined)} buy recommendation(s) in database")

for _, row in refined.iterrows():
    display(Markdown(f"### [{row['title']}]({row['url']})"))
    display(
        Markdown(
            f"*Channel: {row['channel']} | Generated at: {row['recommendations_at']}*"
        )
    )
    display(Markdown(row["buy_recommendations"]))
    display(Markdown("---"))

16:45:18 - INFO - load_summaries() — returned 5 row(s).

5 buy recommendation(s) in database

### [What's Hot & What's Not in an Explosive Pokemon Market](https://www.youtube.com/watch?v=p6aTUw6Cku8)

*Channel: TwicebakedJake | Generated at: 2026-03-05T03:06:59.432754+00:00*

# Pokemon TCG Market Analysis – March 2026

## PER-CARD VERDICTS

| Card | Verdict | Justification |
|------|---------|---------------|
| **151 UPC** | **SKIP** | Video claims ~$700 all-time high; overheated due to recency bias. Jake himself flags this as unsustainable. Charizard UPC ($480) offers better value with tangible pack content. Correction likely when Celebrations hype cools. |
| **Charizard EX (151)** | **SKIP** | Video claims spike from $260→$360 (1-2 months). Verification shows it dropped ~$70 from $300 peak and now trades at $30 PSA 8. Already correcting; momentum reversed. |
| **Charmander Illustration Rare (151)** | **SKIP** | Video flags sharp spike but lacks grading context. Verification shows Charmeleon (169/165) at $69.47 market price with 47 listings—supply is increasing and price stabilizing. Riding 151 wave; expect pullback post-set rotation. |
| **Mega Gengar EX (Ascended Heroes)** | **BUY** | Video notes jump from <$100 (1 yr ago) to $500+ raw; claims "most consistently climbing." Verification confirms holofoil at $950.42 market price with only 14 copies listed / 12 sellers—extreme scarcity + sustained demand. PSA 10 pops likely minimal. Strong fundamentals. |
| **Greninja ex (Shrouded Fables promo)** | **BUY** | Video highlights limited supply (single wave, unreplaced) + high demand. Verification confirms $60 current value, up from ~$30 last summer. Promo exclusivity creates natural supply cap. Steady climb validates thesis. |
| **Special Delivery Charizard** | **BUY** | Video notes 5-6 year dormancy ($100→$40-50→climbing now) + Japanese market tailwinds. Vintage nostalgia + international demand support. Breakout after long underperformance = reversal play. |
| **Sabrina's Gengar & Vintage Gengar** | **BUY** | Video emphasizes "hottest Pokemon in vintage era"; low PSA 10 pops; "skyrocketing" prices. Gengar is top-3 nostalgia driver (alongside Charizard, Mewtwo). Vintage scarcity + collector mania = multi-year upside. |
| **Prismatic Evolution Surprise Box** | **SKIP** | Video flags promo devalued by restocks; packs alone ~$10. Sealed product durability broken; liquidation risk. |
| **Surging Sparks Booster Box** | **SKIP** | Video shows flat performance ($260→$250 YoY); overshadowed by newer sets. "Old news" post-restock. Fair entry but no alpha opportunity. |
| **Pokemon Center Promo Boxes (Tohoku, etc.)** | **SKIP** | Video notes $200-360 (summer 2025) → $160 (now). Restocks triggered panic selling; vendor liquidation ongoing. Dead momentum. |
| **Charizard V Secret Rare (Champions Path)** | **SKIP** | Video calls it "flatline"; competing full art cannibalize demand. Set boring; no collector excitement. No thesis. |
| **Suicune V (Crown Zenith Gallery)** | **SKIP** | Video: cool art but stagnant despite sealed pack gains. Pack openings flood singles supply, inverting typical sealed→singles arbitrage. Supply curve unfavorable. |
| **Mega Ultra Rare Cards** (Charizard, Dragapult, Gardevoir ex, Lucario ex) | **SKIP** | Video: not climbing vs. SIR counterparts; Gardevoir ex & Lucario ex "consistently dropping." Weaker Pokemon + inferior scarcity profile vs. SIRs. |
| **Radiant Collection Raikou** | **SKIP** | Video: flatlined ~$100 after mid-2025 spike. One-off momentum exhausted; no new catalyst visible. |
| **Paradox Pokemon (Ancient Roar, Future Flash) &

---

### [Day 208 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemoncards #pokemontcg](https://www.youtube.com/watch?v=1KijlyGIm0g)

*Channel: Danny Phantump | Generated at: 2026-03-05T03:07:16.430821+00:00*

# Pokemon TCG Market Analysis: Shining Fates Final Cards

## Per-Card Verdicts

| Card | Verdict | Justification |
|------|---------|---------------|
| **Drizzile Baby Shiny** | **BUY** | Undervalued. Market price $3.33 with recent sales at $2.75–$3.40. High liquidity (158 qty, 109 sellers) suggests stable, accessible entry point. Low risk for collection completion. |
| **Corviknight Baby Shiny** | **BUY** | Undervalued. Current market at $1.16 is extremely accessible. Despite a -23% monthly decline, this represents a floor price for a Shining Fates Shiny variant. Minimal downside risk. |
| **Charizard V-Max** | **SKIP** | Fairly priced but risky. Market price $143.89 vs. recent sale $160.00 shows volatility. At $134–$178 range, this is a premium card with moderate daily volume (2 sales/day). High opportunity cost vs. lower-tier Shinies. Better ROI elsewhere. |
| **Crobat Baby Shiny** | **BUY** | Undervalued with upside potential. Market price $73.22 vs. listed median $93.99 indicates buying pressure. Low qty (17) and low seller count (8) suggest scarcity; recent sale at $87.99 supports higher valuation. Potential for appreciation. |

---

## Top Picks (Ranked by Value Opportunity)

### 1. **Corviknight Baby Shiny** ⭐⭐⭐
- **Why**: Rock-bottom price ($1.16) with minimal downside and high upside. Baby Shinies from Shining Fates have demonstrated recovery potential after initial reprint pressure.
- **Action**: Buy multiple copies if available.

### 2. **Crobat Baby Shiny** ⭐⭐⭐
- **Why**: Significant gap between market price ($73.22) and listed median ($93.99) signals undervaluation. Very low inventory (17 qty, 8 sellers) = scarcity. Recent sales at $87.99 validate higher pricing.
- **Action**: Priority acquisition for collection completion.

### 3. **Drizzile Baby Shiny** ⭐⭐
- **Why**: Fair entry point at $3.33 with high liquidity reducing risk. Stable pricing across channels suggests fair valuation; limited upside but reliable for set completion.
- **Action**: Buy as part of bulk Shining Fates acquisition.

### 4. **Charizard V-Max** ⚠️
- **Why**: Premium pricing with no margin of safety. Volatility ($134–$178 range) and moderate daily volume (2 sales/day) suggest speculative rather than speculative upside.
- **Action**: Skip unless critical for set completion; prioritize lower-tier cards first.

---

## Summary
**Best strategy**: Buy the three Shiny cards (Corviknight, Crobat, Drizzile) in sequence, starting with Corviknight for maximum value. Skip Charizard V-Max unless prices drop 15%+ or inventory tightens significantly.

---

### [How Buying Cards in 2026 Feels Like](https://www.youtube.com/watch?v=3lj68hbPojQ)

*Channel: TwicebakedJake | Generated at: 2026-04-07T04:53:15.754213+00:00*

# Buy Recommendations Analysis

## Per-Card Verdicts
**No specific cards identified** — The video contains no concrete card names, set information, or individual price points to evaluate.

---

## Assessment

This video is **not actionable for investment purposes** because:

1. **No substantive data provided** — The content is purely satirical/comedic commentary without specific card recommendations
2. **Hyperbolic pricing claims** — The "$600 billion" reference is explicitly humorous, not a market forecast
3. **No verification possible** — Without card names, grades, or sets, there's nothing to cross-reference against eBay sold listings or current market data
4. **Entertainment, not analysis** — The video serves as commentary on market anxiety rather than a buying guide

---

## Recommendation

**Skip acting on this video for purchasing decisions.**

If you're looking to identify undervalued cards in the current market, I'd recommend:
- Seeking out videos with **specific card evaluations** (name, set, grade, recent comps)
- Cross-referencing claimed prices against **TCGPlayer, eBay sold listings, and PSA/BGS pricing**
- Looking for content from creators who provide **concrete market data** rather than speculative humor

Would you like me to analyze a different video or help evaluate specific cards you're considering?

---

### [Day 241 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemontcg #pokemoncards](https://www.youtube.com/watch?v=awdv1xidtGw)

*Channel: Danny Phantump | Generated at: 2026-04-07T04:53:26.696882+00:00*

# Buy Recommendations Analysis

## Per-Card Verdicts

| Card Name | Verdict | Justification |
|-----------|---------|---------------|
| **Rocket's Moltres EX** | **SKIP** | **Significant price variance detected.** The video describes this as "absolutely stunning" (positive sentiment suggesting acquisition), but market data shows extreme price fragmentation: standard holofoil copies trade at $0.89 on TCGplayer, while the Special Illustration Rare variant (229/182) commands $74.99. Without clarification on which version was acquired, the standard version is drastically overvalued by sentiment relative to actual market price. The SIR variant is a different product entirely. **Recommendation**: If you acquired the standard holofoil, this was likely a fair/undervalued pick at bulk pricing. If interested in the SIR, $74.99 is at market rate but represents a premium collectible tier. |

---

## Top Picks (Ranked)

### Ranking: **No Strong Buy Opportunity Identified**

**Rationale:**
- **Limited data set**: Only one specific card is priced in the verification data
- **No undervalued cards confirmed**: Rocket's Moltres EX (standard) at $0.89 suggests bulk acquisition rather than targeted undervalued picks
- **Team Rocket Returns context**: The creator correctly identifies EX-era sets as expensive and scarce—this is accurate market feedback, meaning most TRR cards are fairly to overpriced relative to nostalgia premiums

---

## Strategic Observations for the Collection

1. **Bulk acquisition approach recommended**: Given the creator's 50% completion rate on TRR (104/208 cards), acquiring remaining cards through bulk lots or trade channels may yield better value than chasing individual cards at market rate

2. **Condition premium alert**: The video notes sourcing "decent condition" is difficult—expect 10-30% premiums for LP/NM copies in EX era sets. Factor this into your budget

3. **Variant awareness**: The SIR Moltres ($74.99) vs. standard ($0.89) shows massive variance. Clarify target grades and variants before purchasing to avoid overpaying for premium versions

---

**Bottom Line**: Continue the set collection strategy, but prioritize bulk sourcing and condition-aware pricing over individual chase cards.

---

### [Day 242 of Collecting EVERY Pokemon Card Master Set! #pokemon #pokemontcg #pokemoncards](https://www.youtube.com/watch?v=2u9GyPkR3y8)

*Channel: Danny Phantump | Generated at: 2026-04-08T08:45:07.981809+00:00*

# Buy Recommendations Analysis

## Issue: Insufficient Data for Analysis

**I cannot provide actionable buy/sell verdicts** because the video summary contains **no specific card names, prices, or market data**.

### What's Missing:
1. ❌ **No card names mentioned** — The summary references "reverse holos," "holo rares," and "higher-value cards" but doesn't identify which specific cards
2. ❌ **No asking prices** — No price points claimed in the video to compare against market data
3. ❌ **No market verification data** — No eBay comps, TCGPlayer listings, or sold prices provided for analysis
4. ❌ **No grading info** — No PSA/BGS grades, which heavily influence Pokémon card pricing

---

## What Would Enable Analysis:

To produce meaningful buy recommendations, I would need:

- **Specific card names** (e.g., "Holo Rare Charizard from Sandstorm")
- **Video's claimed prices** for each card discussed
- **Verification data**: Recent eBay sold listings, TCGPlayer mid prices, or other market comps
- **Grading details** (raw vs. graded, grade level if applicable)

---

## Interim Observation:

The video focuses on **set completion progress** rather than **market analysis or buying opportunities**. If you have access to specific card names and prices from this video, please provide them and I can deliver targeted buy/skip verdicts with ranked value opportunities.

---

## Pending (unverified summaries)

In [8]:
pending = db.get_unverified_summaries()
print(f"{len(pending)} summary/summaries not yet verified")
if not pending.empty:
    display(pending[["video_id", "channel", "title"]])

16:45:18 - INFO - get_unverified_summaries() — 0 summary/summaries pending verification.

0 summary/summaries not yet verified